/**
 * Action types.
 * @module constants/ActionTypes
 */

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const UPDATE_ADDRESS_SUGGESTION_VALUE = 'UPDATE_ADDRESS_SUGGESTION_VALUE';
export const FETCH_ADDRESS_SUGGESTIONS = 'FETCH_ADDRESS_SUGGESTIONS';
export const CLEAR_ADDRESS_SUGGESTIONS = 'CLEAR_ADDRESS_SUGGESTIONS';
export const FETCH_CARD = 'FETCH_CARD';
export const FETCH_CARDS = 'FETCH_CARDS';
export const FETCH_CITY_GEOMETRY = 'FETCH_CITY_GEOMETRY';
export const FETCH_SERVICES = 'FETCH_SERVICES';
export const SET_SORT = 'SET_SORT';
export const INIT_SERVICE_FILTER = 'INIT_SERVICE_FILTER';
export const TOGGLE_SERVICE_FILTER = 'TOGGLE_SERVICE_FILTER';
export const TOGGLE_THEME_FILTER = 'TOGGLE_THEME_FILTER';
export const APP_CONFIG = 'APP_CONFIG';
export const FETCH_PLACE_LOCATION = 'FETCH_PLACE_LOCATION';
export const SET_WEEKLY_ENABLED = 'SET_WEEKLY_ENABLED';
export const GET_WEEKLY_ENABLED_STATUS = 'GET_WEEKLY_ENABLED_STATUS';
export const CONTACT = 'CONTACT';
export const SEND_FIRST_NEWSLETTER = 'SEND_FIRST_NEWSLETTER';
export const UPDATE_PLACE_SETTINGS = 'UPDATE_PLACE_SETTINGS';
